# Generated by Django 4.1.7 on 2023-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
